### ISSUE TITLE
Protonvpn fails to start

### ISSUE THREAD

**Issue by ThomasTraineau** [Rafficer/linux-cli-community#332]
Looks like there has been a python update on arch linux and there is a problem when starting protonvpn, I am getting this output :

```
Traceback (most recent call last):
  File "/usr/bin/protonvpn", line 33, in <module>
    sys.exit(load_entry_point('protonvpn-cli==2.2.11', 'console_scripts', 'protonvpn')())
  File "/usr/bin/protonvpn", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for protonvpn-cli
```
I am using artix linux with python 3.10.1

**Comment by ThomasTraineau** [comment]
I installed it with pip3 and now it seems to be working again

**Comment by eljejer** [comment]
Same issue here as well. Indeed sudo pip3 install protonvpn-cli resolved it.
