### ISSUE TITLE
[BUG] cannot login to protonvpn-cli

### ISSUE THREAD

**Issue by hitchhooker** [Rafficer/linux-cli-community#346]
/home/satoshi/Software〉protonvpn-cli login account 09/18/2022 12:20:03 AM
--> no reaction when trying to login after installing on latest endeavourOS(arch) .
is there way to debug this software somehow? cant find .pvpn-cli logs either.

**Comment by hitchhooker** [comment]
```
^C^CTraceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/secretstorage/util.py", line 48, in send_and_get_reply
    raise DBusErrorResponse(resp_msg)
jeepney.wrappers.DBusErrorResponse: [org.freedesktop.DBus.Error.UnknownMethod] ('Object does not exist at path “/org/freedesktop/secrets/collection/login”',)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/secretstorage/collection.py", line 177, in get_default_collection
    return Collection(connection)
  File "/usr/lib/python3.10/site-packages/secretstorage/collection.py", line 45, in __init__
    self._collection.get_property('Label')
  File "/usr/lib/python3.10/site-packages/secretstorage/util.py", line 67, in get_property
    (signature, value), = self.send_and_get_reply(msg)
  File "/usr/lib/python3.10/site-packages/secretstorage/util.py", line 52, in send_and_get_reply
    raise ItemNotFoundException('Item does not exist!') from resp
secretstorage.exceptions.ItemNotFoundException: Item does not exist!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/protonvpn-cli", line 33, in <module>
    sys.exit(load_entry_point('protonvpn-cli==3.13.0', 'console_scripts', 'protonvpn-cli')())
  File "/usr/lib/python3.10/site-packages/protonvpn_cli/main.py", line 21, in main
    ProtonVPNCLI()
  File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli.py", line 65, in __init__
    res = getattr(self, args.command)()
  File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli.py", line 71, in c
    return self.connect()
  File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli.py", line 133, in connect
    return self.cli_wrapper.connect(args)
  File "/usr/lib/python3.10/site-packages/protonvpn_cli/cli_wrapper.py", line 242, in connect
    if not self.protonvpn.check_session_exists():
  File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/api.py", line 356, in check_session_exists
    return self._env.api_session.is_valid
  File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/environment.py", line 56, in api_session
    self.__api_session = APISession()
  File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/session/session.py", line 240, in __init__
    self.__keyring_load_session()
  File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/session/session.py", line 269, in __keyring_load_session
    keyring_data_user = ExecutionEnvironment().keyring[
  File "/usr/lib/python3.10/site-packages/protonvpn_nm_lib/core/keyring/linuxkeyring.py", line 21, in __getitem__
    stored_data = self.__keyring_backend.get_password(
  File "/usr/lib/python3.10/site-packages/keyring/backends/SecretService.py", line 78, in get_password
    collection = self.get_preferred_collection()
  File "/usr/lib/python3.10/site-packages/keyring/backends/SecretService.py", line 61, in get_preferred_collection
    collection = secretstorage.get_default_collection(bus)
  File "/usr/lib/python3.10/site-packages/secretstorage/collection.py", line 179, in get_default_collection
    return create_collection(connection, 'Default', 'default', session)
  File "/usr/lib/python3.10/site-packages/secretstorage/collection.py", line 157, in create_collection
    dismissed, result = exec_prompt(connection, prompt)
  File "/usr/lib/python3.10/site-packages/secretstorage/util.py", line 145, in exec_prompt
    dismissed, result = connection.recv_until_filtered(signals).body
  File "/usr/lib/python3.10/site-packages/jeepney/io/blocking.py", line 242, in recv_until_filtered
    self.recv_messages(timeout=deadline_to_timeout(deadline))
  File "/usr/lib/python3.10/site-packages/jeepney/io/blocking.py", line 172, in recv_messages
    msg = self.receive(timeout=timeout)
  File "/usr/lib/python3.10/site-packages/jeepney/io/blocking.py", line 165, in receive
    return self._receive(timeout_to_deadline(timeout))
  File "/usr/lib/python3.10/site-packages/jeepney/io/blocking.py", line 102, in _receive
    b, fds = self._read_some_data(timeout=deadline_to_timeout(deadline))
  File "/usr/lib/python3.10/site-packages/jeepney/io/blocking.py", line 106, in _read_some_data
    for key, ev in self.selector.select(timeout):
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
```
