### ISSUE TITLE
[BUG] Can't launch protonvpn or protonvpn-cli

### ISSUE THREAD

**Issue by shift-runstop** [Rafficer/linux-cli-community#348]
When trying to log in with protonvpn-cli I get this err:

```sh
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/keyring/linuxkeyring.py", line 21, in __getitem__
    stored_data = self.__keyring_backend.get_password(
  File "/usr/lib/python3/dist-packages/keyring/backends/SecretService.py", line 78, in get_password
    collection = self.get_preferred_collection()
  File "/usr/lib/python3/dist-packages/keyring/backends/SecretService.py", line 61, in get_preferred_collection
    collection = secretstorage.get_default_collection(bus)
  File "/usr/lib/python3/dist-packages/secretstorage/collection.py", line 177, in get_default_collection
    return Collection(connection)
  File "/usr/lib/python3/dist-packages/secretstorage/collection.py", line 45, in __init__
    self._collection.get_property('Label')
  File "/usr/lib/python3/dist-packages/secretstorage/util.py", line 67, in get_property
    (signature, value), = self.send_and_get_reply(msg)
  File "/usr/lib/python3/dist-packages/secretstorage/util.py", line 48, in send_and_get_reply
    raise DBusErrorResponse(resp_msg)
jeepney.wrappers.DBusErrorResponse: [org.freedesktop.DBus.Error.TimedOut] ("Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=120000ms)",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/protonvpn-cli", line 11, in <module>
    load_entry_point('protonvpn-cli==3.13.0', 'console_scripts', 'protonvpn-cli')()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/main.py", line 21, in main
    ProtonVPNCLI()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli.py", line 65, in __init__
    res = getattr(self, args.command)()
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli.py", line 162, in login
    return self.cli_wrapper.login(args.username)
  File "/usr/lib/python3/dist-packages/protonvpn_cli/cli_wrapper.py", line 63, in login
    if self.protonvpn.check_session_exists():
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/api.py", line 356, in check_session_exists
    return self._env.api_session.is_valid
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/environment.py", line 56, in api_session
    self.__api_session = APISession()
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 240, in __init__
    self.__keyring_load_session()
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/session/session.py", line 269, in __keyring_load_session
    keyring_data_user = ExecutionEnvironment().keyring[
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/keyring/linuxkeyring.py", line 32, in __getitem__
    raise exceptions.KeyringError(e)
protonvpn_nm_lib.exceptions.KeyringError: [org.freedesktop.DBus.Error.TimedOut] ("Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=120000ms)",)

```

and when launching the app I get the same org.freedesktop.DBus.Error.

Proton VPN CLI v3.13.0 (protonvpn-nm-lib v3.13.0; proton-client v0.7.1)

running on i3-wm, only thing I can thing of might be the problem.

**Comment by shift-runstop** [comment]
mistake, please ignore
