### ISSUE TITLE
Error Getting VPN State [BUG]

### ISSUE THREAD

**Issue by hraP93SZrh** [Rafficer/linux-cli-community#355]
**Describe the bug**
Intermittent pop-up appears stating the above along with a further description, "No logical server could be found."

**To Reproduce**
1. Start ProtonVPN GUI, '/usr/bin/protonvpn'
2. Establish connection.
3. Go about your daily work.
4. Pop-up appears without any prompting and continues.

NOTE:  If the computer is unattended for a few hours, as many as thirty (30) of these pop-ups will populate the screen.

**Expected behavior**
Once a connection is established, there will be no further pop-ups from the GUI.

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**
In addition to the appearance of the pop-up previously described, terminal 'stderr' reports:

```
###  BEGIN TERMINAL CONTENTS  ###
(protonvpn:2665929): Gdk-CRITICAL **: 20:37:57.604: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client_mixin.py:11: Warning: g_main_context_push_thread_default: assertion 'acquired_context' failed
  nm_client = NM.Client.new(None)
/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client_mixin.py:11: Warning: g_main_context_pop_thread_default: assertion 'g_queue_peek_head (stack) == context' failed
  nm_client = NM.Client.new(None)
###  END TERMINAL CONTENTS  ###
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 (Focal Fossa) / Linux Mint 20.3 Una
 - Python Version: Python 3.8.10
 - ProtonVPN-CLI Version: protonvpn-cli --version; Output:  Proton VPN CLI v3.13.0 (protonvpn-nm-lib v3.14.0; proton-client v0.7.1)

**Additional context**
The following line counts are for each of the files listed.
- protonvpn-gui.log:     3,848
- protonvpn-gui.log.1:  40,551
- protonvpn-cli.log:       646

**EXAMPLES**

**From 'protonvpn-gui.log'**
An example of an entry from 'protonvpn-gui.log'.  Thousands of lines of these.  Note error:  _No logical server could be found_.
```
2023-05-10 04:57:14,250 — dashboard.py — ERROR —__on_monitor_vpn:698 — No logical server could be found
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protonvpn_gui/view_model/dashboard.py", line 696, in __on_monitor_vpn
    result = self._get_connected_state()
  File "/usr/lib/python3/dist-packages/protonvpn_gui/view_model/dashboard.py", line 598, in _get_connected_state
    connection_status = protonvpn.get_connection_status()
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/api.py", line 364, in get_connection_status
    return Status().get_active_connection_status()
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/status.py", line 52, in get_active_connection_status
    server = self.server_list.filter(
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/servers/list.py", line 372, in get_fastest_server
    raise exceptions.EmptyServerListError(
protonvpn_nm_lib.exceptions.EmptyServerListError: No logical server could be found
```
**From 'protonvpn-cli.log'**
Nothing much happening in here.
```
-----------	Initialized protonvpn-cli	-----------

-------------------------------------------------
2023-05-10 04:08:56,929 — cli.py — INFO — __init__:29 — Proton VPN CLI v3.13.0 (protonvpn-nm-lib v3.14.0; proton-client v0.7.1)
2023-05-10 04:41:46,896 — cli.py — INFO — __init__:17 — 
-------------------------------------------------

-----------	Initialized protonvpn-cli	-----------

-------------------------------------------------
2023-05-10 04:41:46,896 — cli.py — INFO — __init__:29 — Proton VPN CLI v3.13.0 (protonvpn-nm-lib v3.14.0; proton-client v0.7.1)
```

**External IP Address**
The externally confirmed IP address appears to be normal even as the pop-ups appear and are cleared.  Currently reporting 146.70.202.147, New York, NY 10123.

**Final Note**
During the preparation of this report, approximately five (5) of the above described pop-up error messages appeared and were cleared.

**Comment by Jomosoto** [comment]
This repository is an unofficial cli for ProtonVPN. The issue seems to be with the official ProtonVPN GUI. Please report it in https://github.com/ProtonVPN/linux-app
