### ISSUE TITLE
[BUG] Arch Empty Server Pool

### ISSUE THREAD

**Issue by ProgKing** [Rafficer/linux-cli-community#377]
I have this error on my Arch Linux after fresh install: 
Traceback (most recent call last):
  File "/usr/bin/protonvpn", line 33, in <module>
    sys.exit(load_entry_point('protonvpn-cli==2.2.12', 'console_scripts', 'protonvpn')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protonvpn_cli/cli.py", line 72, in main
    cli()
  File "/usr/lib/python3.12/site-packages/protonvpn_cli/cli.py", line 121, in cli
    connection.fastest(protocol)
  File "/usr/lib/python3.12/site-packages/protonvpn_cli/connection.py", line 180, in fastest
    fastest_server = get_fastest_server(server_pool)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protonvpn_cli/utils.py", line 180, in get_fastest_server
    fastest_server = random.choice(fastest_pool[:pool_size])["Name"]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/random.py", line 347, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence

**Comment by ACR-Jeff** [comment]
Exact same issue in void linux

**Comment by ACR-Jeff** [comment]
Well shoot, It worked right after configuring, Now it's throwing errors on `protonvpn status` Going to have to check the errors.

**Comment by ACR-Jeff** [comment]
Well apparently protonvpn still works with the above instructions, The only time I've gotten an error is while using `protonvpn status` I will continue to test.

**Comment by Tamaranch** [comment]
Ah yes, it works again. No need to reconfigure in my case, so the problem must have been with the upstream data format. `protonvpn status` also fails for me.

**Comment by Tamaranch** [comment]
And... broken again :confused:

**Comment by ACR-Jeff** [comment]
Yep seems like proton is trying to go all out and lose customers

**Comment by ACR-Jeff** [comment]
Strange, Without doing anything now today I try it and it works again. Roller coaster ride?
